### ISSUE TITLE
CORS errors

### ISSUE THREAD

**Issue by matthias-luger** [Coflnet/feedback#1]
I get CORS errors if I send a POST request to the endpoint.
![image](https://user-images.githubusercontent.com/58751503/139519641-6c2b5da2-efd9-4874-9d6a-83745cf9282b.png)

Sent data:
`{
    "Context": "Skyblock",
    "User": "104326709973643150510",
    "Feedback": {
        "loadNewInformation": false,
        "otherIssue": false,
        "somethingBroke": false,
        "additionalInformation": "asdf"
    },
    "FeedbackName": "reload"
}`

**Comment by matthias-luger** [comment]
The UI should be finished and can be tested on this branch: https://github.com/Coflnet/hypixel-react/pull/375
To get the dialog, just refresh 2 times.

**Comment by Flou21** [comment]
cors configuration was added with commit https://github.com/Coflnet/feedback/commit/0f902c4888291d847eb20c88480f95d15fdb9e72
